### ISSUE TITLE
Add random ticks window

### ISSUE THREAD

**Issue by RVSkeLe** [OfficialRell/SpawnerMeta#4]
Hi, I've noticed that spawners reset to a fixed default value, unlike vanilla spawners which have a random window (e.g. 536, 495.... instead of 500, 500, 500....).
It would be great to add some kind of window to avoid all the spawners spawning mobs at the same time.

**Comment by OfficialRell** [comment]
Hey! I can add an option to include that in the next update.

**Comment by OfficialRell** [comment]
Option `delay-offset` has been added, by default it is set to 5%
